<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>VIP_AntiFlash</AssemblyName>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>1.0.1-teamfix</InformationalVersion>
    <SdkDirectory Condition="'$(SdkDirectory)' == ''">$(MSBuildThisFileDirectory)../sdk</SdkDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SwiftlyS2.CS2"><HintPath>$(SdkDirectory)/SwiftlyS2.CS2.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions"><HintPath>$(SdkDirectory)/Microsoft.Extensions.Logging.Abstractions.dll</HintPath><Private>false</Private></Reference>
    <ProjectReference Include="../build-support/contract/VIPCore.Contract.csproj" Private="false" />
    <Content Include="resources/**/*"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content>
  </ItemGroup>
</Project>
